import { Artist, MediaContent, Category } from '@/types/supabase-custom';
import { downloadXMLFile } from './helpers';
import { generateArtistXML } from './artists';
import { generateMediaXML } from './media';
import { generateCategoryXML } from './categories';
import { 
  generateSiteOptionsXML, 
  generateThemeSettingsXML, 
  generateActivePluginsXML 
} from './site-options';
import { generateNavigationMenusXML } from './menus';
import { generateStaticPagesXML } from './pages';
import { generateWidgetsXML } from './widgets';
import { 
  generateThemeInstallationXML, 
  generateCustomPostTypesXML, 
  generateACFFieldsXML 
} from './theme';

// Fonction principale d'exportation
export const generateXMLExport = (
  artists: Artist[],
  mediaContents: MediaContent[],
  categories: Category[]
): string => {
  const date = new Date().toISOString();
  const siteTitle = "BkoTube";
  const siteUrl = "https://bkotube.com";
  
  let xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a WordPress eXtended RSS file generated by BkoTube as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<rss version="2.0"
  xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:wfw="http://wellformedweb.org/CommentAPI/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:wp="http://wordpress.org/export/1.2/"
>
<channel>
  <title>${siteTitle}</title>
  <link>${siteUrl}</link>
  <description>Plateforme de contenu musical et vidéo</description>
  <pubDate>${new Date().toUTCString()}</pubDate>
  <language>fr-FR</language>
  <wp:wxr_version>1.2</wp:wxr_version>
  <wp:base_site_url>${siteUrl}</wp:base_site_url>
  <wp:base_blog_url>${siteUrl}</wp:base_blog_url>
  <generator>https://bkotube.com/export</generator>

  <!-- Informations sur l'auteur -->
  <wp:author>
    <wp:author_id>1</wp:author_id>
    <wp:author_login><![CDATA[admin]]></wp:author_login>
    <wp:author_email><![CDATA[admin@bkotube.com]]></wp:author_email>
    <wp:author_display_name><![CDATA[Administrateur]]></wp:author_display_name>
    <wp:author_first_name><![CDATA[Admin]]></wp:author_first_name>
    <wp:author_last_name><![CDATA[BkoTube]]></wp:author_last_name>
  </wp:author>
`;

  // Ajouter les options du site
  xml += generateSiteOptionsXML();
  
  // Ajouter les paramètres du thème
  xml += generateThemeSettingsXML();
  
  // Ajouter les plugins actifs
  xml += generateActivePluginsXML();
  
  // Ajouter les widgets
  xml += generateWidgetsXML();
  
  // Ajouter les informations d'installation du thème
  xml += generateThemeInstallationXML();
  
  // Ajouter les types de contenu personnalisés
  xml += generateCustomPostTypesXML();
  
  // Ajouter les champs personnalisés ACF
  xml += generateACFFieldsXML();

  // Ajouter les types de contenu personnalisés
  xml += `
  <wp:term>
    <wp:term_id>1</wp:term_id>
    <wp:term_taxonomy>post_type</wp:term_taxonomy>
    <wp:term_slug><![CDATA[artiste]]></wp:term_slug>
    <wp:term_name><![CDATA[Artiste]]></wp:term_name>
    <wp:term_description><![CDATA[Type de contenu pour les artistes de BkoTube]]></wp:term_description>
  </wp:term>
  <wp:term>
    <wp:term_id>2</wp:term_id>
    <wp:term_taxonomy>post_type</wp:term_taxonomy>
    <wp:term_slug><![CDATA[media]]></wp:term_slug>
    <wp:term_name><![CDATA[Media]]></wp:term_name>
    <wp:term_description><![CDATA[Type de contenu pour les médias de BkoTube]]></wp:term_description>
  </wp:term>
`;

  // Ajouter les catégories
  categories.forEach(category => {
    xml += generateCategoryXML(category);
  });

  // Ajouter les menus de navigation
  xml += generateNavigationMenusXML();
  
  // Ajouter les pages statiques
  xml += generateStaticPagesXML();

  // Ajouter les artistes
  artists.forEach((artist, index) => {
    xml += generateArtistXML(artist, index);
  });

  // Ajouter les médias
  mediaContents.forEach((media, index) => {
    // Trouver le nom de l'artiste associé
    const artist = artists.find(a => a.id === media.artist_id);
    const category = categories.find(c => c.id === media.category_id);
    
    xml += generateMediaXML(media, artist?.name || '', category?.name || '', index);
  });

  xml += `
</channel>
</rss>`;

  return xml;
};

export { downloadXMLFile };
