// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jssezywnkmepjogzbzez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impzc2V6eXdua21lcGpvZ3piemV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjg5ODQsImV4cCI6MjA1ODYwNDk4NH0.LDlojwf81Xqi2QIOzsjFmDG-eorQ512yzFntOpYZpRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);